import path from 'node:path';

import { describe, expect, it } from 'bun:test';

const cli = path.resolve(import.meta.dir, '../src/cli.ts');

function run(...args: string[]) {
  const result = Bun.spawnSync(['bun', cli, ...args]);
  return {
    exitCode: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

describe('better-auth-workers CLI', () => {
  it('prints the SQL for the requested schema and id type', () => {
    const { exitCode, stdout } = run('sql', '--schema', 'auth_ba', '--id-type', 'uuid');

    expect(exitCode).toBe(0);
    expect(stdout).toStartWith(
      '-- Generated by better-auth-workers sql --schema auth_ba --id-type uuid\n'
    );
    expect(stdout).toContain('create schema if not exists "auth_ba";');
    expect(stdout).toContain('"id" uuid default pg_catalog.gen_random_uuid()');
  });

  it('defaults to public and text ids', () => {
    const { exitCode, stdout } = run('sql');

    expect(exitCode).toBe(0);
    expect(stdout).toContain('create table "user" ("id" text not null primary key');
    expect(stdout).not.toContain('create schema');
  });

  for (const args of [['--help'], ['sql', '--help'], ['sql', '-h']]) {
    it(`prints usage and succeeds for ${args.join(' ')}`, () => {
      const { exitCode, stdout } = run(...args);

      expect(exitCode).toBe(0);
      expect(stdout).toContain('Usage: better-auth-workers sql');
      expect(stdout).not.toContain('create table');
    });
  }

  for (const [label, args, message] of [
    ['no command', [], /Usage/],
    ['an unknown command', ['migrate'], /Unknown command: migrate/],
    ['an unknown option', ['sql', '--dialect', 'sqlite'], /Unknown option/],
    ['an unknown id type', ['sql', '--id-type', 'serial'], /--id-type must be "text" or "uuid"/],
    ['an unsafe schema name', ['sql', '--schema', 'a"b'], /--schema must be/],
  ] as const) {
    it(`fails with ${label}`, () => {
      const { exitCode, stdout, stderr } = run(...args);

      expect(exitCode).toBe(1);
      expect(stdout + stderr).toMatch(message);
    });
  }
});
