#!/usr/bin/env node
import nodeProcess from 'node:process';
import { parseArgs } from 'node:util';

import type { CreateAuthIdType } from './auth/types';
import { generatePostgresSql } from './migrations/generate';

const USAGE = `Usage: better-auth-workers sql [--schema <name>] [--id-type text|uuid]

Prints the Postgres SQL for the tables better-auth-workers uses, matching
the createAuth options of the same names (database.schema, idType).

  --schema <name>     Create the tables in this schema instead of public.
  --id-type <type>    "text" (default) or "uuid".

D1 needs no generation: apply migrations/sqlite from the package as shipped.
`;

const ID_TYPES: readonly string[] = ['text', 'uuid'] satisfies CreateAuthIdType[];

function isIdType(value: string): value is CreateAuthIdType {
  return ID_TYPES.includes(value);
}

class UsageError extends Error {}

// The package's type setup is the Workers runtime's, where `process` is
// untyped; this is the part of Node's the CLI uses.
interface CliProcess {
  argv: string[];
  exitCode?: number;
  stdout: { write: (text: string) => unknown };
  stderr: { write: (text: string) => unknown };
}

const process = nodeProcess as unknown as CliProcess;

async function sqlCommand(args: string[]): Promise<string> {
  const { values } = parseArgs({
    args,
    options: { schema: { type: 'string' }, 'id-type': { type: 'string' } },
    strict: true,
    allowPositionals: false,
  });
  const { schema } = values;
  const idType = values['id-type'] ?? 'text';
  if (!isIdType(idType)) {
    throw new UsageError(`--id-type must be "text" or "uuid", got ${JSON.stringify(idType)}`);
  }
  const sql = await generatePostgresSql({ schema, idType });
  const flags = [schema === undefined ? '' : `--schema ${schema} `, `--id-type ${idType}`].join('');
  return `-- Generated by better-auth-workers sql ${flags}\n-- Database: PostgreSQL\n\n${sql}\n`;
}

async function main(argv: string[]): Promise<number> {
  const command = argv.at(0);
  if (command === '--help' || command === '-h') {
    process.stdout.write(USAGE);
    return 0;
  }
  if (command !== 'sql') {
    const problem = command === undefined ? '' : `Unknown command: ${command}\n\n`;
    process.stderr.write(`${problem}${USAGE}`);
    return 1;
  }
  process.stdout.write(await sqlCommand(argv.slice(1)));
  return 0;
}

try {
  process.exitCode = await main(process.argv.slice(2));
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`better-auth-workers: ${message}\n`);
  process.exitCode = 1;
}
